station1:
  config1:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.400, max_freq : 0.420, min_power_ratio : 0.02 }
  config2:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.400, max_freq : 0.420, min_power_ratio : 0.02 }

station2:
  config1:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.400, max_freq : 0.420, min_power_ratio : 0.02 }
  config2:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.400, max_freq : 0.420, min_power_ratio : 0.02 }

station3:
  config1:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.400, max_freq : 0.420, min_power_ratio : 0.02 }
  config2:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.400, max_freq : 0.420, min_power_ratio : 0.02 }

station4:
  config1:
    excluded_channels : [3, 7, 11, 15] # always exclude string 4
    filters:
      filt1 : { min_freq : 0.400, max_freq : 0.420, min_power_ratio : 0.02 }
  config2:
    excluded_channels : [3, 7, 11, 15] # always exclude string 4
    filters:
      filt1 : { min_freq : 0.400, max_freq : 0.420, min_power_ratio : 0.02 }

station5:
  config1:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.400, max_freq : 0.420, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.135, max_freq : 0.140, min_power_ratio : 0.05 }
      filt3 : { min_freq : 0.150, max_freq : 0.750, min_power_ratio : 0.10 }
  config2:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.400, max_freq : 0.420, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.135, max_freq : 0.140, min_power_ratio : 0.05 }
      filt3 : { min_freq : 0.150, max_freq : 0.750, min_power_ratio : 0.10 }
