station100:
  config1:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.120, max_freq : 0.130, min_power_ratio : 0.02 } # CW @125 MHz
      filt3 : { min_freq : 0.130, max_freq : 0.155, min_power_ratio : 0.01 } # CW @143 MHz
      filt4 : { min_freq : 0.155, max_freq : 0.220, min_power_ratio : 0.10 }
      filt5 : { min_freq : 0.220, max_freq : 0.230, min_power_ratio : 0.02 } # CW @225 MHz
      filt6 : { min_freq : 0.230, max_freq : 0.255, min_power_ratio : 0.02 } # CW @250 MHz
      filt7 : { min_freq : 0.255, max_freq : 0.370, min_power_ratio : 0.10 }
      filt8 : { min_freq : 0.370, max_freq : 0.395, min_power_ratio : 0.02 } # CW @380 MHz
      filt9 : { min_freq : 0.395, max_freq : 0.410, min_power_ratio : 0.01 } # CW @403 MHz (from radiosonde)
      filt10 : { min_freq : 0.410, max_freq : 0.645, min_power_ratio : 0.02 }
      filt11 : { min_freq : 0.645, max_freq : 0.655, min_power_ratio : 0.02 } # CW @650 MHz
      filt12 : { min_freq : 0.655, max_freq : 0.790, min_power_ratio : 0.01 }
      filt13 : { min_freq : 0.790, max_freq : 0.820, min_power_ratio : 0.01 } # CW @809 MHz
      filt14 : { min_freq : 0.820, max_freq : 1.000, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config2:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.120, max_freq : 0.130, min_power_ratio : 0.02 } # CW @125 MHz
      filt3 : { min_freq : 0.130, max_freq : 0.155, min_power_ratio : 0.01 } # CW @143 MHz
      filt4 : { min_freq : 0.155, max_freq : 0.220, min_power_ratio : 0.10 }
      filt5 : { min_freq : 0.220, max_freq : 0.230, min_power_ratio : 0.02 } # CW @225 MHz
      filt6 : { min_freq : 0.230, max_freq : 0.255, min_power_ratio : 0.02 } # CW @250 MHz
      filt7 : { min_freq : 0.255, max_freq : 0.370, min_power_ratio : 0.10 }
      filt8 : { min_freq : 0.370, max_freq : 0.395, min_power_ratio : 0.02 } # CW @380 MHz
      filt9 : { min_freq : 0.395, max_freq : 0.410, min_power_ratio : 0.01 } # CW @403 MHz (from radiosonde)
      filt10 : { min_freq : 0.410, max_freq : 0.645, min_power_ratio : 0.02 }
      filt11 : { min_freq : 0.645, max_freq : 0.655, min_power_ratio : 0.02 } # CW @650 MHz
      filt12 : { min_freq : 0.655, max_freq : 0.790, min_power_ratio : 0.01 }
      filt13 : { min_freq : 0.790, max_freq : 0.820, min_power_ratio : 0.01 } # CW @809 MHz
      filt14 : { min_freq : 0.820, max_freq : 1.000, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config3:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.120, max_freq : 0.130, min_power_ratio : 0.02 } # CW @125 MHz
      filt3 : { min_freq : 0.130, max_freq : 0.155, min_power_ratio : 0.01 } # CW @143 MHz
      filt4 : { min_freq : 0.155, max_freq : 0.220, min_power_ratio : 0.10 }
      filt5 : { min_freq : 0.220, max_freq : 0.230, min_power_ratio : 0.02 } # CW @225 MHz
      filt6 : { min_freq : 0.230, max_freq : 0.255, min_power_ratio : 0.02 } # CW @250 MHz
      filt7 : { min_freq : 0.255, max_freq : 0.370, min_power_ratio : 0.10 }
      filt8 : { min_freq : 0.370, max_freq : 0.395, min_power_ratio : 0.02 } # CW @380 MHz
      filt9 : { min_freq : 0.395, max_freq : 0.410, min_power_ratio : 0.01 } # CW @403 MHz (from radiosonde)
      filt10 : { min_freq : 0.410, max_freq : 0.645, min_power_ratio : 0.02 }
      filt11 : { min_freq : 0.645, max_freq : 0.655, min_power_ratio : 0.02 } # CW @650 MHz
      filt12 : { min_freq : 0.655, max_freq : 0.790, min_power_ratio : 0.01 }
      filt13 : { min_freq : 0.790, max_freq : 0.820, min_power_ratio : 0.01 } # CW @809 MHz
      filt14 : { min_freq : 0.820, max_freq : 1.000, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 8
station2:
  config1:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.138, min_power_ratio : 0.10 }
      filt3 : { min_freq : 0.138, max_freq : 0.149, min_power_ratio : 0.02 } # Targetting 142 and 146 MHz
      filt4 : { min_freq : 0.149, max_freq : 0.248, min_power_ratio : 0.10 }
      filt5 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt6 : { min_freq : 0.254, max_freq : 0.376, min_power_ratio : 0.10 }
      filt7 : { min_freq : 0.376, max_freq : 0.382, min_power_ratio : 0.02 } # Targeting 379 MHz
      filt8 : { min_freq : 0.382, max_freq : 0.400, min_power_ratio : 0.10 } 
      filt9 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.02 } # Targeting 404 MHz
      filt10 : { min_freq : 0.408, max_freq : 1.000, min_power_ratio : 0.10 }
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config2:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.138, min_power_ratio : 0.10 }
      filt3 : { min_freq : 0.138, max_freq : 0.149, min_power_ratio : 0.02 } # Targetting 142 and 146 MHz
      filt4 : { min_freq : 0.149, max_freq : 0.248, min_power_ratio : 0.10 }
      filt5 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt6 : { min_freq : 0.254, max_freq : 0.376, min_power_ratio : 0.10 }
      filt7 : { min_freq : 0.376, max_freq : 0.382, min_power_ratio : 0.02 } # Targeting 379 MHz
      filt8 : { min_freq : 0.382, max_freq : 0.400, min_power_ratio : 0.10 } 
      filt9 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.02 } # Targeting 404 MHz
      filt10 : { min_freq : 0.408, max_freq : 1.000, min_power_ratio : 0.10 }
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config3:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.138, min_power_ratio : 0.10 }
      filt3 : { min_freq : 0.138, max_freq : 0.149, min_power_ratio : 0.02 } # Targetting 142 and 146 MHz
      filt4 : { min_freq : 0.149, max_freq : 0.248, min_power_ratio : 0.10 }
      filt5 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt6 : { min_freq : 0.254, max_freq : 0.376, min_power_ratio : 0.10 }
      filt7 : { min_freq : 0.376, max_freq : 0.382, min_power_ratio : 0.02 } # Targeting 379 MHz
      filt8 : { min_freq : 0.382, max_freq : 0.400, min_power_ratio : 0.10 } 
      filt9 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.02 } # Targeting 404 MHz
      filt10 : { min_freq : 0.408, max_freq : 1.000, min_power_ratio : 0.10 }
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config4:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.138, min_power_ratio : 0.10 }
      filt3 : { min_freq : 0.138, max_freq : 0.149, min_power_ratio : 0.02 } # Targetting 142 and 146 MHz
      filt4 : { min_freq : 0.149, max_freq : 0.248, min_power_ratio : 0.10 }
      filt5 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt6 : { min_freq : 0.254, max_freq : 0.376, min_power_ratio : 0.10 }
      filt7 : { min_freq : 0.376, max_freq : 0.382, min_power_ratio : 0.02 } # Targeting 379 MHz
      filt8 : { min_freq : 0.382, max_freq : 0.400, min_power_ratio : 0.10 } 
      filt9 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.02 } # Targeting 404 MHz
      filt10 : { min_freq : 0.408, max_freq : 1.000, min_power_ratio : 0.10 }
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config5:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.138, min_power_ratio : 0.10 }
      filt3 : { min_freq : 0.138, max_freq : 0.149, min_power_ratio : 0.02 } # Targetting 142 and 146 MHz
      filt4 : { min_freq : 0.149, max_freq : 0.248, min_power_ratio : 0.10 }
      filt5 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt6 : { min_freq : 0.254, max_freq : 0.376, min_power_ratio : 0.10 }
      filt7 : { min_freq : 0.376, max_freq : 0.382, min_power_ratio : 0.02 } # Targeting 379 MHz
      filt8 : { min_freq : 0.382, max_freq : 0.400, min_power_ratio : 0.10 } 
      filt9 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.02 } # Targeting 404 MHz
      filt10 : { min_freq : 0.408, max_freq : 1.000, min_power_ratio : 0.10 }
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config6:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.138, min_power_ratio : 0.10 }
      filt3 : { min_freq : 0.138, max_freq : 0.149, min_power_ratio : 0.02 } # Targetting 142 and 146 MHz
      filt4 : { min_freq : 0.149, max_freq : 0.248, min_power_ratio : 0.10 }
      filt5 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt6 : { min_freq : 0.254, max_freq : 0.376, min_power_ratio : 0.10 }
      filt7 : { min_freq : 0.376, max_freq : 0.382, min_power_ratio : 0.02 } # Targeting 379 MHz
      filt8 : { min_freq : 0.382, max_freq : 0.400, min_power_ratio : 0.10 } 
      filt9 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.02 } # Targeting 404 MHz
      filt10 : { min_freq : 0.408, max_freq : 1.000, min_power_ratio : 0.10 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
  config7:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.138, min_power_ratio : 0.10 }
      filt3 : { min_freq : 0.138, max_freq : 0.149, min_power_ratio : 0.02 } # Targetting 142 and 146 MHz
      filt4 : { min_freq : 0.149, max_freq : 0.248, min_power_ratio : 0.10 }
      filt5 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt6 : { min_freq : 0.254, max_freq : 0.376, min_power_ratio : 0.10 }
      filt7 : { min_freq : 0.376, max_freq : 0.382, min_power_ratio : 0.02 } # Targeting 379 MHz
      filt8 : { min_freq : 0.382, max_freq : 0.400, min_power_ratio : 0.10 } 
      filt9 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.02 } # Targeting 404 MHz
      filt10 : { min_freq : 0.408, max_freq : 1.000, min_power_ratio : 0.10 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
station3:
  config1:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.124, max_freq : 0.126, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.149, max_freq : 0.151, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.249, max_freq : 0.251, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.400, max_freq : 0.406, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config2:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.124, max_freq : 0.126, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.149, max_freq : 0.151, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.249, max_freq : 0.251, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.400, max_freq : 0.406, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config3:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.124, max_freq : 0.126, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.149, max_freq : 0.151, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.249, max_freq : 0.251, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.400, max_freq : 0.406, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config4:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.124, max_freq : 0.126, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.149, max_freq : 0.151, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.249, max_freq : 0.251, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.400, max_freq : 0.406, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config5:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.124, max_freq : 0.126, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.149, max_freq : 0.151, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.249, max_freq : 0.251, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.404, max_freq : 0.406, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config6:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.124, max_freq : 0.126, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.149, max_freq : 0.151, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.249, max_freq : 0.251, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.404, max_freq : 0.406, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
  config7:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.124, max_freq : 0.126, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.149, max_freq : 0.151, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.249, max_freq : 0.251, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.404, max_freq : 0.406, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
  config8:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.124, max_freq : 0.126, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.149, max_freq : 0.151, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.249, max_freq : 0.251, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.404, max_freq : 0.406, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
  config9:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.124, max_freq : 0.126, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.149, max_freq : 0.151, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.249, max_freq : 0.251, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.404, max_freq : 0.406, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
station4:
  config1:
    excluded_channels : [3, 7, 11, 15] # always exclude string 4
    filters:
      filt1 : { min_freq : 0.212, max_freq : 0.225, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.400, max_freq : 0.407, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.650, max_freq : 0.659, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 10
  config2:
    excluded_channels : [3, 7, 11, 15] # always exclude string 4
    filters:
      filt1 : { min_freq : 0.212, max_freq : 0.225, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.400, max_freq : 0.407, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.650, max_freq : 0.659, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 10
  config3:
    excluded_channels : [3, 7, 11, 15] # always exclude string 4
    filters:
      filt1 : { min_freq : 0.212, max_freq : 0.225, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.400, max_freq : 0.407, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.650, max_freq : 0.659, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 32
      soft_readout_limit: 10
  config4:
    excluded_channels : [3, 7, 11, 15] # always exclude string 4
    filters:
      filt1 : { min_freq : 0.212, max_freq : 0.225, min_power_ratio : 0.02 }
      filt2 : { min_freq : 0.400, max_freq : 0.407, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.650, max_freq : 0.659, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 32
      soft_readout_limit: 10
station5:
  config1:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.140, min_power_ratio : 0.05 }
      filt3 : { min_freq : 0.140, max_freq : 0.320, min_power_ratio : 0.10 }
      filt4 : { min_freq : 0.320, max_freq : 0.340, min_power_ratio : 0.02 }
      filt5 : { min_freq : 0.340, max_freq : 0.495, min_power_ratio : 0.10 }
      filt6 : { min_freq : 0.495, max_freq : 0.510, min_power_ratio : 0.02 }
      filt7 : { min_freq : 0.510, max_freq : 1.000, min_power_ratio : 0.10 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 10
  config2:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 0.120, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.140, min_power_ratio : 0.05 }
      filt3 : { min_freq : 0.140, max_freq : 0.320, min_power_ratio : 0.10 }
      filt4 : { min_freq : 0.320, max_freq : 0.340, min_power_ratio : 0.02 }
      filt5 : { min_freq : 0.340, max_freq : 0.495, min_power_ratio : 0.10 }
      filt6 : { min_freq : 0.495, max_freq : 0.510, min_power_ratio : 0.02 }
      filt7 : { min_freq : 0.510, max_freq : 1.000, min_power_ratio : 0.10 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 10
