station100:
  config1:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.200, max_freq : 0.580, min_power_ratio : 0.05 }
      filt3 : { min_freq : 0.120, max_freq : 0.126, min_power_ratio : 0.02 } # CW @125 MHz
      filt4 : { min_freq : 0.220, max_freq : 0.228, min_power_ratio : 0.02 } # CW @225 MHz
      filt5 : { min_freq : 0.245, max_freq : 0.255, min_power_ratio : 0.02 } # CW @250 MHz
      filt6 : { min_freq : 0.645, max_freq : 0.655, min_power_ratio : 0.02 } # CW @650 MHz
      filt7 : { min_freq : 0.805, max_freq : 0.815, min_power_ratio : 0.02 } # CW @809 MHz
      filt8 : { min_freq : 0.140, max_freq : 0.155, min_power_ratio : 0.01 } # CW @143 MHz
      filt9 : { min_freq : 0.396, max_freq : 0.410, min_power_ratio : 0.01 } # CW @403 MHz (from radiosonde)

    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config2:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.200, max_freq : 0.580, min_power_ratio : 0.05 }
      filt3 : { min_freq : 0.120, max_freq : 0.126, min_power_ratio : 0.02 } # CW @125 MHz
      filt4 : { min_freq : 0.220, max_freq : 0.228, min_power_ratio : 0.02 } # CW @225 MHz
      filt5 : { min_freq : 0.245, max_freq : 0.255, min_power_ratio : 0.02 } # CW @250 MHz
      filt6 : { min_freq : 0.374, max_freq : 0.382, min_power_ratio : 0.02 } # CW @378 MHz
      filt7 : { min_freq : 0.645, max_freq : 0.655, min_power_ratio : 0.02 } # CW @650 MHz
      filt8 : { min_freq : 0.805, max_freq : 0.815, min_power_ratio : 0.02 } # CW @809 MHz
      filt9 : { min_freq : 0.140, max_freq : 0.155, min_power_ratio : 0.01 } # CW @143 MHz
      filt10 : { min_freq : 0.396, max_freq : 0.410, min_power_ratio : 0.01 } # CW @403 MHz (from radiosonde)
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config3:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.200, max_freq : 0.580, min_power_ratio : 0.05 }
      filt3 : { min_freq : 0.120, max_freq : 0.126, min_power_ratio : 0.02 } # CW @125 MHz
      filt4 : { min_freq : 0.220, max_freq : 0.228, min_power_ratio : 0.02 } # CW @225 MHz
      filt5 : { min_freq : 0.245, max_freq : 0.255, min_power_ratio : 0.02 } # CW @250 MHz
      filt6 : { min_freq : 0.645, max_freq : 0.655, min_power_ratio : 0.02 } # CW @650 MHz
      filt7 : { min_freq : 0.805, max_freq : 0.815, min_power_ratio : 0.02 } # CW @809 MHz
      filt8 : { min_freq : 0.140, max_freq : 0.155, min_power_ratio : 0.01 } # CW @143 MHz
      filt9 : { min_freq : 0.396, max_freq : 0.410, min_power_ratio : 0.01 } # CW @403 MHz (from radiosonde)
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 8
station2:
  config1:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.045, max_freq : 0.160, min_power_ratio : 0.001 } # Targets 60 MHz peak seen in spectra and something around 110 MHz and broadband from ~121-155 found by PV
      filt2 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt3 : { min_freq : 0.376, max_freq : 0.410, min_power_ratio : 0.02  } # Targeting 379 MHz and 404 MHz
      filt4 : { min_freq : 0.440, max_freq : 0.460, min_power_ratio : 0.005 } # Targeting 450 MHz
      filt5 : { min_freq : 0.497, max_freq : 0.533, min_power_ratio : 0.001 } # Targeting 502 MHz and 528 MHz
      filt6 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10  } # Broad, high power, cleanup filter 
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config2:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.045, max_freq : 0.160, min_power_ratio : 0.001 } # Targets 60 MHz peak seen in spectra and something around 110 MHz and broadband from ~121-155 found by PV
      filt2 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt3 : { min_freq : 0.376, max_freq : 0.410, min_power_ratio : 0.02  } # Targeting 379 MHz and 404 MHz
      filt4 : { min_freq : 0.440, max_freq : 0.460, min_power_ratio : 0.005 } # Targeting 450 MHz
      filt5 : { min_freq : 0.497, max_freq : 0.533, min_power_ratio : 0.001 } # Targeting 502 MHz and 528 MHz
      filt6 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10  } # Broad, high power, cleanup filter 
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config3:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.045, max_freq : 0.160, min_power_ratio : 0.001 } # Targets 60 MHz peak seen in spectra and something around 110 MHz and broadband from ~121-155 found by PV
      filt2 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt3 : { min_freq : 0.376, max_freq : 0.410, min_power_ratio : 0.02  } # Targeting 379 MHz and 404 MHz
      filt4 : { min_freq : 0.440, max_freq : 0.460, min_power_ratio : 0.005 } # Targeting 450 MHz
      filt5 : { min_freq : 0.497, max_freq : 0.533, min_power_ratio : 0.001 } # Targeting 502 MHz and 528 MHz
      filt6 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10  } # Broad, high power, cleanup filter 
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config4:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.045, max_freq : 0.160, min_power_ratio : 0.001 } # Targets 60 MHz peak seen in spectra and something around 110 MHz and broadband from ~121-155 found by PV
      filt2 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt3 : { min_freq : 0.376, max_freq : 0.410, min_power_ratio : 0.02  } # Targeting 379 MHz and 404 MHz
      filt4 : { min_freq : 0.440, max_freq : 0.460, min_power_ratio : 0.005 } # Targeting 450 MHz
      filt5 : { min_freq : 0.497, max_freq : 0.533, min_power_ratio : 0.001 } # Targeting 502 MHz and 528 MHz
      filt6 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10  } # Broad, high power, cleanup filter 
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config5:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.045, max_freq : 0.160, min_power_ratio : 0.001 } # Targets 60 MHz peak seen in spectra and something around 110 MHz and broadband from ~121-155 found by PV
      filt2 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt3 : { min_freq : 0.376, max_freq : 0.410, min_power_ratio : 0.02  } # Targeting 379 MHz and 404 MHz
      filt4 : { min_freq : 0.440, max_freq : 0.460, min_power_ratio : 0.005 } # Targeting 450 MHz
      filt5 : { min_freq : 0.497, max_freq : 0.533, min_power_ratio : 0.001 } # Targeting 502 MHz and 528 MHz
      filt6 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10  } # Broad, high power, cleanup filter 
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config6:
    excluded_channels : [15] # always exclude channel 15
    filters:
      filt1 : { min_freq : 0.045, max_freq : 0.160, min_power_ratio : 0.001 } # Targets 60 MHz peak seen in spectra and something around 110 MHz and broadband from ~121-155 found by PV
      filt2 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt3 : { min_freq : 0.376, max_freq : 0.410, min_power_ratio : 0.02  } # Targeting 379 MHz and 404 MHz
      filt4 : { min_freq : 0.440, max_freq : 0.460, min_power_ratio : 0.005 } # Targeting 450 MHz
      filt5 : { min_freq : 0.497, max_freq : 0.533, min_power_ratio : 0.001 } # Targeting 502 MHz and 528 MHz
      filt6 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10  } # Broad, high power, cleanup filter 
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
  config7:
    excluded_channels : [0, 4, 8, 12, 15] # always exclude channel 15, also exclude string 1 for duplication issue and misreconstructing calpulsers
    filters:
      filt1 : { min_freq : 0.045, max_freq : 0.160, min_power_ratio : 0.001 } # Targets 60 MHz peak seen in spectra and something around 110 MHz and broadband from ~121-155 found by PV
      filt2 : { min_freq : 0.248, max_freq : 0.254, min_power_ratio : 0.005 } # Targeting 251 MHz
      filt3 : { min_freq : 0.376, max_freq : 0.410, min_power_ratio : 0.02  } # Targeting 379 MHz and 404 MHz
      filt4 : { min_freq : 0.440, max_freq : 0.460, min_power_ratio : 0.005 } # Targeting 450 MHz
      filt5 : { min_freq : 0.497, max_freq : 0.533, min_power_ratio : 0.001 } # Targeting 502 MHz and 528 MHz
      filt6 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10  } # Broad, high power, cleanup filter 
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
station3:
  config1:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.155, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.245, max_freq : 0.255, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.295, max_freq : 0.305, min_power_ratio : 0.011 }
      filt5 : { min_freq : 0.398, max_freq : 0.408, min_power_ratio : 0.01 }
      filt6 : { min_freq : 0.495, max_freq : 0.505, min_power_ratio : 0.01 }
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config2:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.155, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.245, max_freq : 0.255, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.295, max_freq : 0.305, min_power_ratio : 0.011 }
      filt5 : { min_freq : 0.398, max_freq : 0.408, min_power_ratio : 0.01 }
      filt6 : { min_freq : 0.495, max_freq : 0.505, min_power_ratio : 0.01 }
    readout_limits:
      rf_readout_limit: 20
      soft_readout_limit: 8
  config3:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.195, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.245, max_freq : 0.255, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.295, max_freq : 0.305, min_power_ratio : 0.01 }
      filt5 : { min_freq : 0.398, max_freq : 0.408, min_power_ratio : 0.01 }
      filt6 : { min_freq : 0.495, max_freq : 0.505, min_power_ratio : 0.005 }
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config4:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.128, min_power_ratio : 0.001 }
      filt3 : { min_freq : 0.140, max_freq : 0.330, min_power_ratio : 0.01 }
      filt4 : { min_freq : 0.370, max_freq : 0.408, min_power_ratio : 0.01 }
      filt5 : { min_freq : 0.430, max_freq : 0.510, min_power_ratio : 0.01 }
      filt6 : { min_freq : 0.580, max_freq : 0.620, min_power_ratio : 0.01 } 
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config5:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.155, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.235, max_freq : 0.255, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.290, max_freq : 0.330, min_power_ratio : 0.02 }
      filt5 : { min_freq : 0.400, max_freq : 0.470, min_power_ratio : 0.01 }
      filt6 : { min_freq : 0.495, max_freq : 0.510, min_power_ratio : 0.02 }
      filt7 : { min_freq : 0.580, max_freq : 0.620, min_power_ratio : 0.02 }
    readout_limits:
      rf_readout_limit: 26
      soft_readout_limit: 8
  config6:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.155, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.240, max_freq : 0.255, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.295, max_freq : 0.330, min_power_ratio : 0.002 }
      filt5 : { min_freq : 0.400, max_freq : 0.410, min_power_ratio : 0.002 }
      filt6 : { min_freq : 0.495, max_freq : 0.510, min_power_ratio : 0.002 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
  config7:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.155, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.240, max_freq : 0.255, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.295, max_freq : 0.330, min_power_ratio : 0.005 }
      filt5 : { min_freq : 0.400, max_freq : 0.430, min_power_ratio : 0.007 }
      filt6 : { min_freq : 0.495, max_freq : 0.510, min_power_ratio : 0.005 }
      filt7 : { min_freq : 0.580, max_freq : 0.620, min_power_ratio : 0.01 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
  config8:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.155, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.190, max_freq : 0.210, min_power_ratio : 0.02 }
      filt4 : { min_freq : 0.240, max_freq : 0.305, min_power_ratio : 0.02 }
      filt5 : { min_freq : 0.400, max_freq : 0.510, min_power_ratio : 0.01 }
      filt6 : { min_freq : 0.580, max_freq : 0.620, min_power_ratio : 0.01 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
  config9:
    excluded_channels : [3, 7, 11, 15]
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.210, min_power_ratio : 0.02 }
      filt3 : { min_freq : 0.245, max_freq : 0.280, min_power_ratio : 0.01 }
      filt4 : { min_freq : 0.295, max_freq : 0.305, min_power_ratio : 0.005 }
      filt5 : { min_freq : 0.370, max_freq : 0.385, min_power_ratio : 0.02 }
      filt6 : { min_freq : 0.385, max_freq : 0.410, min_power_ratio : 0.005 }
      filt7 : { min_freq : 0.430, max_freq : 0.470, min_power_ratio : 0.01 }
      filt8 : { min_freq : 0.495, max_freq : 0.510, min_power_ratio : 0.005 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 12
station4:
  config1:
    excluded_channels : [3, 7, 11, 15] # always exclude string 4
    filters:
      filt1 : { min_freq : 0.0, max_freq : 1.000, min_power_ratio : 0.1 }
      filt2 : { min_freq : 0.140, max_freq : 0.150, min_power_ratio : 0.01 }
      filt3 : { min_freq : 0.211, max_freq : 0.228, min_power_ratio : 0.01 }
      filt4 : { min_freq : 0.375, max_freq : 0.385, min_power_ratio : 0.001 }
      filt5 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.001 } # Major Radiosonde
      filt6 : { min_freq : 0.408, max_freq : 0.500, min_power_ratio : 0.01 }
      filt7 : { min_freq : 0.650, max_freq : 0.660, min_power_ratio : 0.0006 } # Major A4's private property
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 10
  config2:
    excluded_channels : [3, 7, 11, 15] # always exclude string 4
    filters:
      filt1 : { min_freq : 0.0, max_freq : 1.000, min_power_ratio : 0.1 }
      filt2 : { min_freq : 0.140, max_freq : 0.150, min_power_ratio : 0.01 }
      filt3 : { min_freq : 0.211, max_freq : 0.228, min_power_ratio : 0.01 }
      filt4 : { min_freq : 0.375, max_freq : 0.385, min_power_ratio : 0.001 }
      filt5 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.001 } # Major Radiosonde
      filt6 : { min_freq : 0.408, max_freq : 0.500, min_power_ratio : 0.01 }
      filt7 : { min_freq : 0.650, max_freq : 0.660, min_power_ratio : 0.0006 } # Major A4's private property
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 10
  config3:
    excluded_channels : [3, 7, 11, 15] # always exclude string 4
    filters:
      filt1 : { min_freq : 0.0, max_freq : 1.000, min_power_ratio : 0.1 }
      filt2 : { min_freq : 0.140, max_freq : 0.150, min_power_ratio : 0.01 }
      filt3 : { min_freq : 0.211, max_freq : 0.228, min_power_ratio : 0.01 }
      filt4 : { min_freq : 0.375, max_freq : 0.385, min_power_ratio : 0.001 }
      filt5 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.001 } # Major Radiosonde
      filt6 : { min_freq : 0.408, max_freq : 0.500, min_power_ratio : 0.01 }
      filt7 : { min_freq : 0.650, max_freq : 0.660, min_power_ratio : 0.0006 } # Major A4's private property
    readout_limits:
      rf_readout_limit: 32
      soft_readout_limit: 10
  config4:
    excluded_channels : [3, 7, 11, 15] # always exclude string 4
    filters:
      filt1 : { min_freq : 0.0, max_freq : 1.000, min_power_ratio : 0.1 }
      filt2 : { min_freq : 0.140, max_freq : 0.150, min_power_ratio : 0.01 }
      filt3 : { min_freq : 0.211, max_freq : 0.228, min_power_ratio : 0.01 }
      filt4 : { min_freq : 0.375, max_freq : 0.385, min_power_ratio : 0.001 }
      filt5 : { min_freq : 0.400, max_freq : 0.408, min_power_ratio : 0.001 } # Major Radiosonde
      filt6 : { min_freq : 0.408, max_freq : 0.500, min_power_ratio : 0.01 }
      filt7 : { min_freq : 0.650, max_freq : 0.660, min_power_ratio : 0.0006 } # Major A4's private property

    readout_limits:
      rf_readout_limit: 32
      soft_readout_limit: 10
station5:
  config1:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.045, max_freq : 0.127, min_power_ratio : 0.0001}
      filt3 : { min_freq : 0.127, max_freq : 0.160, min_power_ratio : 0.001 }
      filt4 : { min_freq : 0.200, max_freq : 0.290, min_power_ratio : 0.01 }
      filt5 : { min_freq : 0.220, max_freq : 0.240, min_power_ratio : 0.001 }
      filt7 : { min_freq : 0.290, max_freq : 0.310, min_power_ratio : 0.001 }
      filt8 : { min_freq : 0.310, max_freq : 0.590, min_power_ratio : 0.02 }
      filt9 : { min_freq : 0.390, max_freq : 0.420, min_power_ratio : 0.002 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 10
  config2:
    excluded_channels : []
    filters:
      filt1 : { min_freq : 0.000, max_freq : 1.000, min_power_ratio : 0.10 }
      filt2 : { min_freq : 0.120, max_freq : 0.160, min_power_ratio : 0.0006 }
      filt3 : { min_freq : 0.200, max_freq : 0.220, min_power_ratio : 0.010 }
      filt4 : { min_freq : 0.220, max_freq : 0.260, min_power_ratio : 0.001 }
      filt5 : { min_freq : 0.260, max_freq : 0.510, min_power_ratio : 0.02 }
      filt6 : { min_freq : 0.380, max_freq : 0.420, min_power_ratio : 0.001 }
    readout_limits:
      rf_readout_limit: 28
      soft_readout_limit: 10

